import numpy as np


class MahjongHands:
    _hand_titles = np.array([
        "Hand Names",
        "Terminal/non-dragon honor pung",
        "2x identical chows, same suit",
        "2x identical chows, 2 suits",
        "6-tile straight, same suit",
        "123 and 789 same suit",
        "Melded (revealed) kong",
        "Voided suit",
        "No honor tiles",
        "Edge wait",
        "Closed wait",
        "Single wait",
        "Self-drawn",
        "Dragon pung",
        "Round wind pung",
        "Seat wind pung",
        "Concealed hand, discard win",
        "All chows, no honors",
        "Tile hog",
        "2x pung, same number, diff. suits",
        "2x concealed pung",
        "Concealed kong",
        "All simples (2-8 only)",
        "Outside hand (term/honor in each set)",
        "Fully concealed, self draw win",
        "2x melded kong",
        "Last tile",
        "All pungs",
        "Half flush (one suit + honors)",
        "Mixed shifted chow",
        "All types",
        "Melded hand",
        "2x dragon pung",
        "Melded + unmelded kong",
        "Mixed straight",
        "Reversible tiles",
        "Mixed triple chow (same chow, 3 suits)",
        "Mixed shifted pungs",
        "Chicken hand",
        "Last tile draw",
        "Last tile claim",
        "Replacement win",
        "Kong rob",
        "2x concealed kong",
        "Lesser Honors + Knitted sequence",
        "Knitted Straight",
        "Upper Four (6-9 suit tiles only)",
        "Lower Four (1-4 suit tiles only)",
        "Big Three Winds (3 wind pung/kongs)",
        "Pure Straight (1-9 same suit)",
        "Three-suited terminal chows",
        "Pure Shifted Chows",
        "All 5s",
        "Triple Pung",
        "3x Concealed Pungs",
        "Seven Pairs",
        "Greater Honors and Knitted Tiles",
        "All Even Pungs",
        "Full Flush (All tiles in the same suit)",
        "Pure Triple Chow",
        "Pure Shifted Pungs",
        "Upper Tiles (7-9 tiles, suits only)",
        "Middle Tiles (4-6 tiles, suits only)",
        "Lower Tiles (1-3 tiles, suits only)",
        "Four Shifted Chows",
        "Three Kongs",
        "All terminals + honors",
        "Quad Chow (4x same chow)",
        "Four Pure Shifted Pungs",
        "All terminals",
        "Little 4 Winds",
        "Little 3 Dragons",
        "All Honors",
        "4x Concealed Pungs",
        "Pure Terminal Chows",
        "Big 4 Winds",
        "Big 3 Dragons",
        "All Green",
        "Nine Gates",
        "Four Kongs",
        "Seven Shifted Pairs",
        "Thirteen Orphans"
    ])
    _points = np.array([
        "Point Values",
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        4,
        4,
        4,
        4,
        6,
        6,
        6,
        6,
        6,
        6,
        6,
        8,
        8,
        8,
        8,
        8,
        8,
        8,
        8,
        8,
        8,
        12,
        12,
        12,
        12,
        12,
        16,
        16,
        16,
        16,
        16,
        16,
        24,
        24,
        24,
        24,
        24,
        24,
        24,
        24,
        24,
        32,
        32,
        32,
        48,
        48,
        64,
        64,
        64,
        64,
        64,
        64,
        88,
        88,
        88,
        88,
        88,
        88,
        88
    ])
    _notes = np.array([
        "Notes",
        "Not round/seat, no dragons",
        "",
        "",
        "",
        "",
        "",
        "Hand contains 2/3 suits and optionally honors. Missing one suit entirely",
        "",
        ("Winning on 3 to finish a 123 or a 7 to finish a 789 ONLY. Must be the only possible tile to complete 4 SETS "
         "AND PAIR. Doesn't count for hands that win with non-4 set + pair hands"),
        ("Winning on the middle piece of a chow. E.g. 2 in a 1-2-3 chow. Must be the only possible tile to complete 4"
         " SETS AND PAIR. Doesn't count for hands that win with non-4 set + pair hands"),
        ("Winning on single tile to form a pair. Must be the only possible tile to complete 4 SETS AND PAIR."
         " Doesn't count for hands that win with non-4 set + pair hands"),
        "",
        "",
        "",
        "",
        "Must win by discard",
        "",
        "Uses all 4 of the same suit tile, but not as a kong. E.g. 123, 333",
        "",
        "",
        "",
        "",
        "Pair must also be terminal/honor",
        "must win by self draw",
        "",
        "can be self drawn or stolen, must be clear from discards/melds and your hand",
        "4 pungs/kongs + pair",
        "one suit only",
        "each chow shifted up by 1. E.g. 456, 567, 678",
        "all sets (including pair) is a unique suit / honor",
        "Must win on discard",
        "can be different dragons",
        "Cannot find this anywhere but mahjongsoft.com",
        "suit 1 - 123 suit 2 - 456 suit 3 - 789",
        "hand contains tiles from 1234589 of dots 245689 bamboo white dragon",
        "each chow must be different suit",
        "3 suits, 3 pungs, each shifted by 1 e.g. 222 333 444",
        "a hand worth 0 points otherwise",
        "self draw the final tile and win",
        "take the final tile after it is discarded and win",
        "declare kong, win off drawn tile. Counts as self-drawn",
        "someone adds a tile to their melded pung to make a kong, but you steal it and win",
        "any 2 kongs",
        ("Suit 1: 147 Suit 2: 248 Suit 3: 369 + all honors = 16 tile set Have 14/16 of this 'set' with NO DUPLICATES."
         " Knitted sequence doesn't need to be a complete straight. CAN combine with knitted straight."),
        ("Suit 1: 147 Suit 2: 248 Suit 3: 369 Have ALL 1-9 of the knitted set + "
         "5 unique honors CAN combine with lesser honors + knitted"),
        "",
        "",
        "",
        "",
        "123,789 in suit 1, 123,789 in suit 2 and 55 pair in third suit",
        "Same suit, 3 chows who's sequences are shifted by 1. Example, 123,234,345",
        "All sets (including pair) has a 5",
        "3 pungs, 3 suits, same number in each",
        "",
        "7 different pairs. No actual sets.",
        ("Suit 1: 147 Suit 2: 248 Suit 3: 369 + all honors = 16 tile set Have ALL honors + 7/16 of this 'set' "
         "with NO DUPLICATES. Knitted sequence doesn't need to be a complete straight. "
         "CAN combine with knitted straight."),
        "No honor tiles allowed",
        "No honor tiles allowed",
        "Same sequence 3 times, same suit. Looks like a 3x pung, but actually is 3x sequences",
        ("Very similar to triple chow. 3 sequential pungs in the same suit (111 222 333). "
         "Can also be used for (but not combined with) pure triple chow. This can also use kongs though, "
         "while triple chow cannot."),
        "",
        "",
        "",
        ("4 chows, same suit, each up by 1 OR 2 numbers but not a combination of both. "
         "Examples: 123 234 345 456 123 345 567 789"),
        "Combines with 3x concealed pung if concealed",
        "",
        "",
        "4x pungs (or kongs) shifted up by 1 each. 111 222 333 444",
        "",
        "3 wind pungs + wind pair. Can combine with seat/round wind points",
        "2 dragon pungs + pair of the 3rd dragon",
        "",
        "",
        "123 123, 789, 789 + 55 pair same suit",
        "pung/kong of all 4 wind tiles",
        "pung/kong of all dragons",
        "23468 of bamboo and/or green dragons only",
        "1112345678999 concealed and winning on a 1-9 of the same suit",
        "",
        "7 pairs each shifted up by 1. Example 22 33 44 55 66 77 88",
        "Singles of all 1,9 from each suit + all honor tiles + 1 duplicate of any"
    ])
    _categories = np.array([
        "Categories",
        "pung, honor, terminal",
        "chow, suit",
        "chow, mixed",
        "chow, straight, suit",
        "chow, straight, terminal, suit",
        "kong, melded",
        "suit",
        "suit, honor",
        "chow, wait, winning",
        "chow, wait, winning",
        "wait, winning",
        "winning",
        "pung, honor, dragon",
        "pung, honor",
        "pung, honor",
        "winning, concealed",
        "chow, winning, honor",
        "winning, chow, pung, kong",
        "pung, suit",
        "pung, concealed",
        "kong, concealed",
        "winning, suit, honor",
        "winning, honor, terminal",
        "winning, concealed",
        "kong, melded",
        "winning",
        "pung, kong",
        "suit, honor",
        "chow, suit",
        "suit, honor",
        "melded, winning",
        "pung, honor, dragon",
        "kong, concealed, melded",
        "chow, suit",
        "suit, winning",
        "chow, suit",
        "pung, suit",
        "winning",
        "winning",
        "winning",
        "kong, winning",
        "kong, winning",
        "kong, concealed",
        "suit, chow, honor, dragon, special",
        "suit, chow, honor, dragon, special, straight",
        "suit, pung, chow, kong, terminal",
        "suit, pung, chow, kong",
        "honor, pung, kong",
        "chow, straight, suit",
        "chow, straight, terminal, suit",
        "chow, straight, suit",
        "suit, chow, pung, kong",
        "pung, suit",
        "pung, concealed",
        "special",
        "suit, chow, honor, dragon, special",
        "suit, pung",
        "suit, pung, chow, kong",
        "suit, chow, pung",
        "suit, pung, kong, chow",
        "suit, chow, pung, kong, terminal",
        "suit, chow, pung, kong",
        "suit, chow, pung, kong, terminal",
        "chow, suit",
        "kong, concealed",
        "honor, pung, kong, chow, terminal",
        "chow, suit",
        "pung, suit, kong",
        "terminal, pung, kong, chow",
        "honor, pung, kong",
        "honor, dragon, pung, kong",
        "honor, dragon, pung, chow, kong",
        "pung, concealed",
        "chow, suit",
        "honor, pung, kong",
        "honor, dragon, pung, kong",
        "suit, honor, dragon, pung, kong, chow",
        "suit, terminal, straight, chow, special, concealed",
        "kong, special",
        "suit, special",
        "special, honor, dragon, terminal"
    ])
    _example_images = np.array([
        "[IMAGE]Example Images",
        "./img/examples/terminal_honor_pung.png",
        "./img/examples/pure_double_chow.png",
        "./img/examples/mixed_double_chow.png",
        "./img/examples/short_straight.png",
        "./img/examples/two_terminal_chow.png",
        "./img/examples/melded_kong.png",
        "./img/examples/voided_suit.png",
        "./img/examples/no_honor.png",
        "./img/examples/edge_wait.png",
        "./img/examples/closed_wait.png",
        "./img/examples/single_wait.png",
        "./img/examples/empty.gif",
        "./img/examples/dragon_pung.png",
        "./img/examples/round_wind_pung.png",
        "./img/examples/seat_wind_pung.png",
        "./img/examples/empty.gif",
        "./img/examples/all_chows.png",
        "./img/examples/tile_hog.png",
        "./img/examples/double_pung.png",
        "./img/examples/empty.gif",
        "./img/examples/empty.gif",
        "./img/examples/all_simples.png",
        "./img/examples/outside_hand.png",
        "./img/examples/empty.gif",
        "./img/examples/two_kongs.png",
        "./img/examples/empty.gif",
        "./img/examples/all_pungs.png",
        "./img/examples/half_flush.png",
        "./img/examples/mixed_shifted_chows.png",
        "./img/examples/all_types.png",
        "./img/examples/empty.gif",
        "./img/examples/two_dragon_pungs.png",
        "./img/examples/empty.gif",
        "./img/examples/mixed_straight.png",
        "./img/examples/reversible_tiles.png",
        "./img/examples/mixed_triple_chow.png",
        "./img/examples/mixed_shifted_pungs.png",
        "./img/examples/empty.gif",
        "./img/examples/empty.gif",
        "./img/examples/empty.gif",
        "./img/examples/empty.gif",
        "./img/examples/empty.gif",
        "./img/examples/empty.gif",
        "./img/examples/lesser_honors_and_knitted_tiles.png",
        "./img/examples/knitted_straight.png",
        "./img/examples/upper_four.png",
        "./img/examples/lower_four.png",
        "./img/examples/big_three_winds.png",
        "./img/examples/empty.gif",
        "./img/examples/empty.gif",
        "./img/examples/empty.gif",
        "./img/examples/empty.gif",
        "./img/examples/empty.gif",
        "./img/examples/empty.gif",
        "./img/examples/empty.gif",
        "./img/examples/empty.gif",
        "./img/examples/empty.gif",
        "./img/examples/empty.gif",
        "./img/examples/empty.gif",
        "./img/examples/empty.gif",
        "./img/examples/empty.gif",
        "./img/examples/empty.gif",
        "./img/examples/empty.gif",
        "./img/examples/empty.gif",
        "./img/examples/empty.gif",
        "./img/examples/empty.gif",
        "./img/examples/empty.gif",
        "./img/examples/empty.gif",
        "./img/examples/empty.gif",
        "./img/examples/empty.gif",
        "./img/examples/empty.gif",
        "./img/examples/empty.gif",
        "./img/examples/empty.gif",
        "./img/examples/empty.gif",
        "./img/examples/empty.gif",
        "./img/examples/empty.gif",
        "./img/examples/empty.gif",
        "./img/examples/empty.gif",
        "./img/examples/empty.gif",
        "./img/examples/empty.gif",
        "./img/examples/empty.gif"
    ])

    @staticmethod
    def sort_list(arr):
        new_arr = []
        for cat in arr:
            cat_list = cat.split(",")
            cat_list = list(map(lambda x: x.strip(), cat_list))
            cat_list = sorted(cat_list)
            cat_list = ", ".join(cat_list)
            new_arr += [cat_list]
        return np.array(new_arr)

    _categories = sort_list(_categories)
    hands_info = np.vstack((_hand_titles, _points, _categories, _notes, _example_images)).T

